/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sandornemeth' at '5/20/14 8:05 PM' with Gradle 1.12
 *
 * @author sandornemeth, @date 5/20/14 8:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
